### ISSUE TITLE
SUMMARY: Exceeds Expectations

### ISSUE THREAD

**Issue by jzhu01** [GoodMattwin/Jammming#6]
Nice job on this project! I really liked how you added in the searching when a user presses enter, as well as how you coded for an error to popup in case the request returned anything aside from ok when searching. 

In terms of improvement, you don't need to the condition for onAdd in track.js, or searchTerm in App,js. I also suggest only creating variables where you will reuse them. 

I really liked your tidbits that you added to the code. Keep up the fantastic work! :D

**Comment by GoodMattwin** [comment]
Thank you!
